# Generated by Django 2.2.10 on 2021-05-04 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Polls',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('from_date', models.DateField(verbose_name='Дата старта')),
                ('to_date', models.DateField(verbose_name='Дата окончания')),
                ('description', models.TextField(
                    max_length=500, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опросы',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Тест вопроса')),
                ('type', models.CharField(choices=[('0', 'ответ текстом'), ('1', 'ответ с выбором одного варианта'),
                                                   ('2', 'ответ с выбором нескольких вариантов')], default='1',
                                          max_length=2, verbose_name='Тип вопроса')),
                ('polls',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='polls.Polls',
                                   verbose_name='Опрос')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Текст ответа')),
                ('is_valid', models.BooleanField(
                    default=False, verbose_name='Верный')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question',
                                               verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответов',
            },
        ),
    ]
