# Generated by Django 2.2.10 on 2021-05-05 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('polls', '0002_question_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options',
                                    to='polls.Question', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.CharField(
                max_length=300, verbose_name='Текст вопроса'),
        ),
        migrations.CreateModel(
            name='UserStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(
                    verbose_name='ID Пользователя')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Answer',
                                             verbose_name='Опрос')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question',
                                               verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
    ]
