# Generated by Django 2.2.10 on 2021-05-05 08:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('polls', '0004_auto_20210505_0654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='is_valid',
        ),
    ]
